{{- if not .Values.isClient }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tunnel.fullname" . }}
  labels:
    {{- include "tunnel.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tunnel.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tunnel.fullname" . }}-external
  labels:
    {{- include "tunnel.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http-external
  selector:
    {{- include "tunnel.selectorLabels" . | nindent 4 }}
{{- end}}